// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbp5Mr8yQvxbundkW3NEeFFCN5O9BRqms',
    appId: '1:154103086037:android:4dfb864fa028e807fa5b5c',
    messagingSenderId: '154103086037',
    projectId: 'festa-dev-a42a6',
    storageBucket: 'festa-dev-a42a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa3vvpMRYrvZlZoszWxT2hZJgh1n5lE34',
    appId: '1:154103086037:ios:80ae21b940fde469fa5b5c',
    messagingSenderId: '154103086037',
    projectId: 'festa-dev-a42a6',
    storageBucket: 'festa-dev-a42a6.appspot.com',
    androidClientId: '154103086037-3a5hbvmkmnnean1scr2vh3tq0natpjgj.apps.googleusercontent.com',
    iosClientId: '154103086037-0nncc86gh56hmc9qu682qm598n1rg9cm.apps.googleusercontent.com',
    iosBundleId: 'com.festaworld.app',
  );
}
